/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as RefundsIndexRouteImport } from './routes/refunds/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CheckoutsIndexRouteImport } from './routes/checkouts/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as RefundsNewRouteImport } from './routes/refunds/new'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as PaymentsNewRouteImport } from './routes/payments/new'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CheckoutsNewRouteImport } from './routes/checkouts/new'
import { Route as CategoriesNewRouteImport } from './routes/categories/new'
import { Route as BrandsNewRouteImport } from './routes/brands/new'
import { Route as CustomersGroupsIndexRouteImport } from './routes/customers/groups/index'
import { Route as CustomersAddressesIndexRouteImport } from './routes/customers/addresses/index'
import { Route as TransactionsTransactionIdEditRouteImport } from './routes/transactions/$transactionId/edit'
import { Route as RefundsRefundIdEditRouteImport } from './routes/refunds/$refundId/edit'
import { Route as ProductsProductIdEditRouteImport } from './routes/products/$productId/edit'
import { Route as PaymentsPaymentIdEditRouteImport } from './routes/payments/$paymentId/edit'
import { Route as OrdersOrderIdEditRouteImport } from './routes/orders/$orderId/edit'
import { Route as InventoryInventoryLevelIdEditRouteImport } from './routes/inventory/$inventoryLevelId/edit'
import { Route as CustomersAddressesNewRouteImport } from './routes/customers/addresses/new'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers/$customerId/edit'
import { Route as CheckoutsCheckoutIdEditRouteImport } from './routes/checkouts/$checkoutId/edit'
import { Route as CategoriesCategoryIdEditRouteImport } from './routes/categories/$categoryId/edit'
import { Route as BrandsBrandIdEditRouteImport } from './routes/brands/$brandId/edit'
import { Route as CustomersAddressesAddressIdEditRouteImport } from './routes/customers/addresses/$addressId/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsIndexRoute = RefundsIndexRouteImport.update({
  id: '/refunds/',
  path: '/refunds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsIndexRoute = CheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsNewRoute = RefundsNewRouteImport.update({
  id: '/refunds/new',
  path: '/refunds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsNewRoute = CheckoutsNewRouteImport.update({
  id: '/checkouts/new',
  path: '/checkouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewRoute = BrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersGroupsIndexRoute = CustomersGroupsIndexRouteImport.update({
  id: '/customers/groups/',
  path: '/customers/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersAddressesIndexRoute = CustomersAddressesIndexRouteImport.update({
  id: '/customers/addresses/',
  path: '/customers/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdEditRoute =
  TransactionsTransactionIdEditRouteImport.update({
    id: '/transactions/$transactionId/edit',
    path: '/transactions/$transactionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RefundsRefundIdEditRoute = RefundsRefundIdEditRouteImport.update({
  id: '/refunds/$refundId/edit',
  path: '/refunds/$refundId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/products/$productId/edit',
  path: '/products/$productId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentIdEditRoute = PaymentsPaymentIdEditRouteImport.update({
  id: '/payments/$paymentId/edit',
  path: '/payments/$paymentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdEditRoute = OrdersOrderIdEditRouteImport.update({
  id: '/orders/$orderId/edit',
  path: '/orders/$orderId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInventoryLevelIdEditRoute =
  InventoryInventoryLevelIdEditRouteImport.update({
    id: '/inventory/$inventoryLevelId/edit',
    path: '/inventory/$inventoryLevelId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersAddressesNewRoute = CustomersAddressesNewRouteImport.update({
  id: '/customers/addresses/new',
  path: '/customers/addresses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/customers/$customerId/edit',
  path: '/customers/$customerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsCheckoutIdEditRoute = CheckoutsCheckoutIdEditRouteImport.update({
  id: '/checkouts/$checkoutId/edit',
  path: '/checkouts/$checkoutId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdEditRoute =
  CategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsBrandIdEditRoute = BrandsBrandIdEditRouteImport.update({
  id: '/brands/$brandId/edit',
  path: '/brands/$brandId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersAddressesAddressIdEditRoute =
  CustomersAddressesAddressIdEditRouteImport.update({
    id: '/customers/addresses/$addressId/edit',
    path: '/customers/addresses/$addressId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/checkouts/new': typeof CheckoutsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/refunds/new': typeof RefundsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/brands': typeof BrandsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkouts': typeof CheckoutsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/refunds': typeof RefundsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/brands/$brandId/edit': typeof BrandsBrandIdEditRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/checkouts/$checkoutId/edit': typeof CheckoutsCheckoutIdEditRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/addresses/new': typeof CustomersAddressesNewRoute
  '/inventory/$inventoryLevelId/edit': typeof InventoryInventoryLevelIdEditRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof PaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/refunds/$refundId/edit': typeof RefundsRefundIdEditRoute
  '/transactions/$transactionId/edit': typeof TransactionsTransactionIdEditRoute
  '/customers/addresses': typeof CustomersAddressesIndexRoute
  '/customers/groups': typeof CustomersGroupsIndexRoute
  '/customers/addresses/$addressId/edit': typeof CustomersAddressesAddressIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/checkouts/new': typeof CheckoutsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/refunds/new': typeof RefundsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/brands': typeof BrandsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkouts': typeof CheckoutsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/refunds': typeof RefundsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/brands/$brandId/edit': typeof BrandsBrandIdEditRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/checkouts/$checkoutId/edit': typeof CheckoutsCheckoutIdEditRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/addresses/new': typeof CustomersAddressesNewRoute
  '/inventory/$inventoryLevelId/edit': typeof InventoryInventoryLevelIdEditRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof PaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/refunds/$refundId/edit': typeof RefundsRefundIdEditRoute
  '/transactions/$transactionId/edit': typeof TransactionsTransactionIdEditRoute
  '/customers/addresses': typeof CustomersAddressesIndexRoute
  '/customers/groups': typeof CustomersGroupsIndexRoute
  '/customers/addresses/$addressId/edit': typeof CustomersAddressesAddressIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/checkouts/new': typeof CheckoutsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/refunds/new': typeof RefundsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkouts/': typeof CheckoutsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/refunds/': typeof RefundsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/brands/$brandId/edit': typeof BrandsBrandIdEditRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/checkouts/$checkoutId/edit': typeof CheckoutsCheckoutIdEditRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/addresses/new': typeof CustomersAddressesNewRoute
  '/inventory/$inventoryLevelId/edit': typeof InventoryInventoryLevelIdEditRoute
  '/orders/$orderId/edit': typeof OrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof PaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/refunds/$refundId/edit': typeof RefundsRefundIdEditRoute
  '/transactions/$transactionId/edit': typeof TransactionsTransactionIdEditRoute
  '/customers/addresses/': typeof CustomersAddressesIndexRoute
  '/customers/groups/': typeof CustomersGroupsIndexRoute
  '/customers/addresses/$addressId/edit': typeof CustomersAddressesAddressIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/brands/new'
    | '/categories/new'
    | '/checkouts/new'
    | '/customers/new'
    | '/inventory/new'
    | '/orders/new'
    | '/payments/new'
    | '/products/new'
    | '/refunds/new'
    | '/transactions/new'
    | '/brands'
    | '/categories'
    | '/checkouts'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/products'
    | '/refunds'
    | '/transactions'
    | '/brands/$brandId/edit'
    | '/categories/$categoryId/edit'
    | '/checkouts/$checkoutId/edit'
    | '/customers/$customerId/edit'
    | '/customers/addresses/new'
    | '/inventory/$inventoryLevelId/edit'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/refunds/$refundId/edit'
    | '/transactions/$transactionId/edit'
    | '/customers/addresses'
    | '/customers/groups'
    | '/customers/addresses/$addressId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/brands/new'
    | '/categories/new'
    | '/checkouts/new'
    | '/customers/new'
    | '/inventory/new'
    | '/orders/new'
    | '/payments/new'
    | '/products/new'
    | '/refunds/new'
    | '/transactions/new'
    | '/brands'
    | '/categories'
    | '/checkouts'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/products'
    | '/refunds'
    | '/transactions'
    | '/brands/$brandId/edit'
    | '/categories/$categoryId/edit'
    | '/checkouts/$checkoutId/edit'
    | '/customers/$customerId/edit'
    | '/customers/addresses/new'
    | '/inventory/$inventoryLevelId/edit'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/refunds/$refundId/edit'
    | '/transactions/$transactionId/edit'
    | '/customers/addresses'
    | '/customers/groups'
    | '/customers/addresses/$addressId/edit'
  id:
    | '__root__'
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/brands/new'
    | '/categories/new'
    | '/checkouts/new'
    | '/customers/new'
    | '/inventory/new'
    | '/orders/new'
    | '/payments/new'
    | '/products/new'
    | '/refunds/new'
    | '/transactions/new'
    | '/brands/'
    | '/categories/'
    | '/checkouts/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/payments/'
    | '/products/'
    | '/refunds/'
    | '/transactions/'
    | '/brands/$brandId/edit'
    | '/categories/$categoryId/edit'
    | '/checkouts/$checkoutId/edit'
    | '/customers/$customerId/edit'
    | '/customers/addresses/new'
    | '/inventory/$inventoryLevelId/edit'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/refunds/$refundId/edit'
    | '/transactions/$transactionId/edit'
    | '/customers/addresses/'
    | '/customers/groups/'
    | '/customers/addresses/$addressId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementsRoute: typeof MovementsRoute
  PairingRoute: typeof PairingRoute
  SettingsRoute: typeof SettingsRoute
  BrandsNewRoute: typeof BrandsNewRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  CheckoutsNewRoute: typeof CheckoutsNewRoute
  CustomersNewRoute: typeof CustomersNewRoute
  InventoryNewRoute: typeof InventoryNewRoute
  OrdersNewRoute: typeof OrdersNewRoute
  PaymentsNewRoute: typeof PaymentsNewRoute
  ProductsNewRoute: typeof ProductsNewRoute
  RefundsNewRoute: typeof RefundsNewRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutsIndexRoute: typeof CheckoutsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RefundsIndexRoute: typeof RefundsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  BrandsBrandIdEditRoute: typeof BrandsBrandIdEditRoute
  CategoriesCategoryIdEditRoute: typeof CategoriesCategoryIdEditRoute
  CheckoutsCheckoutIdEditRoute: typeof CheckoutsCheckoutIdEditRoute
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  CustomersAddressesNewRoute: typeof CustomersAddressesNewRoute
  InventoryInventoryLevelIdEditRoute: typeof InventoryInventoryLevelIdEditRoute
  OrdersOrderIdEditRoute: typeof OrdersOrderIdEditRoute
  PaymentsPaymentIdEditRoute: typeof PaymentsPaymentIdEditRoute
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
  RefundsRefundIdEditRoute: typeof RefundsRefundIdEditRoute
  TransactionsTransactionIdEditRoute: typeof TransactionsTransactionIdEditRoute
  CustomersAddressesIndexRoute: typeof CustomersAddressesIndexRoute
  CustomersGroupsIndexRoute: typeof CustomersGroupsIndexRoute
  CustomersAddressesAddressIdEditRoute: typeof CustomersAddressesAddressIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds/': {
      id: '/refunds/'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/': {
      id: '/checkouts/'
      path: '/checkouts'
      fullPath: '/checkouts'
      preLoaderRoute: typeof CheckoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds/new': {
      id: '/refunds/new'
      path: '/refunds/new'
      fullPath: '/refunds/new'
      preLoaderRoute: typeof RefundsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/new': {
      id: '/checkouts/new'
      path: '/checkouts/new'
      fullPath: '/checkouts/new'
      preLoaderRoute: typeof CheckoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new': {
      id: '/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof BrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/groups/': {
      id: '/customers/groups/'
      path: '/customers/groups'
      fullPath: '/customers/groups'
      preLoaderRoute: typeof CustomersGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/addresses/': {
      id: '/customers/addresses/'
      path: '/customers/addresses'
      fullPath: '/customers/addresses'
      preLoaderRoute: typeof CustomersAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId/edit': {
      id: '/transactions/$transactionId/edit'
      path: '/transactions/$transactionId/edit'
      fullPath: '/transactions/$transactionId/edit'
      preLoaderRoute: typeof TransactionsTransactionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds/$refundId/edit': {
      id: '/refunds/$refundId/edit'
      path: '/refunds/$refundId/edit'
      fullPath: '/refunds/$refundId/edit'
      preLoaderRoute: typeof RefundsRefundIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$paymentId/edit': {
      id: '/payments/$paymentId/edit'
      path: '/payments/$paymentId/edit'
      fullPath: '/payments/$paymentId/edit'
      preLoaderRoute: typeof PaymentsPaymentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId/edit': {
      id: '/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof OrdersOrderIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$inventoryLevelId/edit': {
      id: '/inventory/$inventoryLevelId/edit'
      path: '/inventory/$inventoryLevelId/edit'
      fullPath: '/inventory/$inventoryLevelId/edit'
      preLoaderRoute: typeof InventoryInventoryLevelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/addresses/new': {
      id: '/customers/addresses/new'
      path: '/customers/addresses/new'
      fullPath: '/customers/addresses/new'
      preLoaderRoute: typeof CustomersAddressesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/$checkoutId/edit': {
      id: '/checkouts/$checkoutId/edit'
      path: '/checkouts/$checkoutId/edit'
      fullPath: '/checkouts/$checkoutId/edit'
      preLoaderRoute: typeof CheckoutsCheckoutIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/edit': {
      id: '/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof CategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/edit': {
      id: '/brands/$brandId/edit'
      path: '/brands/$brandId/edit'
      fullPath: '/brands/$brandId/edit'
      preLoaderRoute: typeof BrandsBrandIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/addresses/$addressId/edit': {
      id: '/customers/addresses/$addressId/edit'
      path: '/customers/addresses/$addressId/edit'
      fullPath: '/customers/addresses/$addressId/edit'
      preLoaderRoute: typeof CustomersAddressesAddressIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementsRoute: MovementsRoute,
  PairingRoute: PairingRoute,
  SettingsRoute: SettingsRoute,
  BrandsNewRoute: BrandsNewRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  CheckoutsNewRoute: CheckoutsNewRoute,
  CustomersNewRoute: CustomersNewRoute,
  InventoryNewRoute: InventoryNewRoute,
  OrdersNewRoute: OrdersNewRoute,
  PaymentsNewRoute: PaymentsNewRoute,
  ProductsNewRoute: ProductsNewRoute,
  RefundsNewRoute: RefundsNewRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutsIndexRoute: CheckoutsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RefundsIndexRoute: RefundsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  BrandsBrandIdEditRoute: BrandsBrandIdEditRoute,
  CategoriesCategoryIdEditRoute: CategoriesCategoryIdEditRoute,
  CheckoutsCheckoutIdEditRoute: CheckoutsCheckoutIdEditRoute,
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  CustomersAddressesNewRoute: CustomersAddressesNewRoute,
  InventoryInventoryLevelIdEditRoute: InventoryInventoryLevelIdEditRoute,
  OrdersOrderIdEditRoute: OrdersOrderIdEditRoute,
  PaymentsPaymentIdEditRoute: PaymentsPaymentIdEditRoute,
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
  RefundsRefundIdEditRoute: RefundsRefundIdEditRoute,
  TransactionsTransactionIdEditRoute: TransactionsTransactionIdEditRoute,
  CustomersAddressesIndexRoute: CustomersAddressesIndexRoute,
  CustomersGroupsIndexRoute: CustomersGroupsIndexRoute,
  CustomersAddressesAddressIdEditRoute: CustomersAddressesAddressIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
