/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as DebtorsIndexRouteImport } from './routes/debtors/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as DebtorsNewRouteImport } from './routes/debtors/new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsIndexRoute = DebtorsIndexRouteImport.update({
  id: '/debtors/',
  path: '/debtors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorsNewRoute = DebtorsNewRouteImport.update({
  id: '/debtors/new',
  path: '/debtors/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/debtors/new': typeof DebtorsNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/debtors': typeof DebtorsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/debtors/new': typeof DebtorsNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/debtors': typeof DebtorsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/debtors/new': typeof DebtorsNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/debtors/': typeof DebtorsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/debtors/new'
    | '/inventory/new'
    | '/transactions/new'
    | '/debtors'
    | '/inventory'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/debtors/new'
    | '/inventory/new'
    | '/transactions/new'
    | '/debtors'
    | '/inventory'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/movements'
    | '/pairing'
    | '/settings'
    | '/debtors/new'
    | '/inventory/new'
    | '/transactions/new'
    | '/debtors/'
    | '/inventory/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementsRoute: typeof MovementsRoute
  PairingRoute: typeof PairingRoute
  SettingsRoute: typeof SettingsRoute
  DebtorsNewRoute: typeof DebtorsNewRoute
  InventoryNewRoute: typeof InventoryNewRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  DebtorsIndexRoute: typeof DebtorsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/': {
      id: '/debtors/'
      path: '/debtors'
      fullPath: '/debtors'
      preLoaderRoute: typeof DebtorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtors/new': {
      id: '/debtors/new'
      path: '/debtors/new'
      fullPath: '/debtors/new'
      preLoaderRoute: typeof DebtorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementsRoute: MovementsRoute,
  PairingRoute: PairingRoute,
  SettingsRoute: SettingsRoute,
  DebtorsNewRoute: DebtorsNewRoute,
  InventoryNewRoute: InventoryNewRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  DebtorsIndexRoute: DebtorsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
