/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ShopsNewRouteImport } from './routes/shops/new'
import { Route as ShopsShopIdIndexRouteImport } from './routes/shops/$shopId/index'
import { Route as ShopsShopIdSettingsRouteImport } from './routes/shops/$shopId/settings'
import { Route as ShopsShopIdAddModuleRouteImport } from './routes/shops/$shopId/add-module'
import { Route as ShopsShopIdTransactionsIndexRouteImport } from './routes/shops/$shopId/transactions/index'
import { Route as ShopsShopIdShipmentsIndexRouteImport } from './routes/shops/$shopId/shipments/index'
import { Route as ShopsShopIdReviewsIndexRouteImport } from './routes/shops/$shopId/reviews/index'
import { Route as ShopsShopIdRefundsIndexRouteImport } from './routes/shops/$shopId/refunds/index'
import { Route as ShopsShopIdProductsIndexRouteImport } from './routes/shops/$shopId/products/index'
import { Route as ShopsShopIdPosSessionsIndexRouteImport } from './routes/shops/$shopId/pos-sessions/index'
import { Route as ShopsShopIdPaymentsIndexRouteImport } from './routes/shops/$shopId/payments/index'
import { Route as ShopsShopIdOrdersIndexRouteImport } from './routes/shops/$shopId/orders/index'
import { Route as ShopsShopIdLocationsIndexRouteImport } from './routes/shops/$shopId/locations/index'
import { Route as ShopsShopIdInventoryIndexRouteImport } from './routes/shops/$shopId/inventory/index'
import { Route as ShopsShopIdInquiriesIndexRouteImport } from './routes/shops/$shopId/inquiries/index'
import { Route as ShopsShopIdCustomersIndexRouteImport } from './routes/shops/$shopId/customers/index'
import { Route as ShopsShopIdCheckoutsIndexRouteImport } from './routes/shops/$shopId/checkouts/index'
import { Route as ShopsShopIdCategoriesIndexRouteImport } from './routes/shops/$shopId/categories/index'
import { Route as ShopsShopIdBrandsIndexRouteImport } from './routes/shops/$shopId/brands/index'
import { Route as ShopsShopIdTransactionsNewRouteImport } from './routes/shops/$shopId/transactions/new'
import { Route as ShopsShopIdRefundsNewRouteImport } from './routes/shops/$shopId/refunds/new'
import { Route as ShopsShopIdProductsNewRouteImport } from './routes/shops/$shopId/products/new'
import { Route as ShopsShopIdPosSessionsNewRouteImport } from './routes/shops/$shopId/pos-sessions/new'
import { Route as ShopsShopIdPaymentsNewRouteImport } from './routes/shops/$shopId/payments/new'
import { Route as ShopsShopIdOrdersNewRouteImport } from './routes/shops/$shopId/orders/new'
import { Route as ShopsShopIdInventoryNewRouteImport } from './routes/shops/$shopId/inventory/new'
import { Route as ShopsShopIdInventoryMovementsRouteImport } from './routes/shops/$shopId/inventory/movements'
import { Route as ShopsShopIdCustomersNewRouteImport } from './routes/shops/$shopId/customers/new'
import { Route as ShopsShopIdCheckoutsNewRouteImport } from './routes/shops/$shopId/checkouts/new'
import { Route as ShopsShopIdCategoriesNewRouteImport } from './routes/shops/$shopId/categories/new'
import { Route as ShopsShopIdBrandsNewRouteImport } from './routes/shops/$shopId/brands/new'
import { Route as ShopsShopIdCustomersGroupsIndexRouteImport } from './routes/shops/$shopId/customers/groups/index'
import { Route as ShopsShopIdCustomersAddressesIndexRouteImport } from './routes/shops/$shopId/customers/addresses/index'
import { Route as ShopsShopIdTransactionsTransactionIdEditRouteImport } from './routes/shops/$shopId/transactions/$transactionId/edit'
import { Route as ShopsShopIdRefundsRefundIdEditRouteImport } from './routes/shops/$shopId/refunds/$refundId/edit'
import { Route as ShopsShopIdProductsProductIdEditRouteImport } from './routes/shops/$shopId/products/$productId/edit'
import { Route as ShopsShopIdPosSessionsPosSessionIdEditRouteImport } from './routes/shops/$shopId/pos-sessions/$posSessionId/edit'
import { Route as ShopsShopIdPaymentsPaymentIdEditRouteImport } from './routes/shops/$shopId/payments/$paymentId/edit'
import { Route as ShopsShopIdOrdersOrderIdEditRouteImport } from './routes/shops/$shopId/orders/$orderId/edit'
import { Route as ShopsShopIdInventoryInventoryLevelIdEditRouteImport } from './routes/shops/$shopId/inventory/$inventoryLevelId/edit'
import { Route as ShopsShopIdCustomersAddressesNewRouteImport } from './routes/shops/$shopId/customers/addresses/new'
import { Route as ShopsShopIdCustomersCustomerIdEditRouteImport } from './routes/shops/$shopId/customers/$customerId/edit'
import { Route as ShopsShopIdCheckoutsCheckoutIdEditRouteImport } from './routes/shops/$shopId/checkouts/$checkoutId/edit'
import { Route as ShopsShopIdCategoriesCategoryIdEditRouteImport } from './routes/shops/$shopId/categories/$categoryId/edit'
import { Route as ShopsShopIdBrandsBrandIdEditRouteImport } from './routes/shops/$shopId/brands/$brandId/edit'
import { Route as ShopsShopIdCustomersAddressesAddressIdEditRouteImport } from './routes/shops/$shopId/customers/addresses/$addressId/edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsNewRoute = ShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdIndexRoute = ShopsShopIdIndexRouteImport.update({
  id: '/shops/$shopId/',
  path: '/shops/$shopId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdSettingsRoute = ShopsShopIdSettingsRouteImport.update({
  id: '/shops/$shopId/settings',
  path: '/shops/$shopId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdAddModuleRoute = ShopsShopIdAddModuleRouteImport.update({
  id: '/shops/$shopId/add-module',
  path: '/shops/$shopId/add-module',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdTransactionsIndexRoute =
  ShopsShopIdTransactionsIndexRouteImport.update({
    id: '/shops/$shopId/transactions/',
    path: '/shops/$shopId/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdShipmentsIndexRoute =
  ShopsShopIdShipmentsIndexRouteImport.update({
    id: '/shops/$shopId/shipments/',
    path: '/shops/$shopId/shipments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdReviewsIndexRoute = ShopsShopIdReviewsIndexRouteImport.update({
  id: '/shops/$shopId/reviews/',
  path: '/shops/$shopId/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRefundsIndexRoute = ShopsShopIdRefundsIndexRouteImport.update({
  id: '/shops/$shopId/refunds/',
  path: '/shops/$shopId/refunds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdProductsIndexRoute =
  ShopsShopIdProductsIndexRouteImport.update({
    id: '/shops/$shopId/products/',
    path: '/shops/$shopId/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdPosSessionsIndexRoute =
  ShopsShopIdPosSessionsIndexRouteImport.update({
    id: '/shops/$shopId/pos-sessions/',
    path: '/shops/$shopId/pos-sessions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdPaymentsIndexRoute =
  ShopsShopIdPaymentsIndexRouteImport.update({
    id: '/shops/$shopId/payments/',
    path: '/shops/$shopId/payments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdOrdersIndexRoute = ShopsShopIdOrdersIndexRouteImport.update({
  id: '/shops/$shopId/orders/',
  path: '/shops/$shopId/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdLocationsIndexRoute =
  ShopsShopIdLocationsIndexRouteImport.update({
    id: '/shops/$shopId/locations/',
    path: '/shops/$shopId/locations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdInventoryIndexRoute =
  ShopsShopIdInventoryIndexRouteImport.update({
    id: '/shops/$shopId/inventory/',
    path: '/shops/$shopId/inventory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdInquiriesIndexRoute =
  ShopsShopIdInquiriesIndexRouteImport.update({
    id: '/shops/$shopId/inquiries/',
    path: '/shops/$shopId/inquiries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersIndexRoute =
  ShopsShopIdCustomersIndexRouteImport.update({
    id: '/shops/$shopId/customers/',
    path: '/shops/$shopId/customers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCheckoutsIndexRoute =
  ShopsShopIdCheckoutsIndexRouteImport.update({
    id: '/shops/$shopId/checkouts/',
    path: '/shops/$shopId/checkouts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCategoriesIndexRoute =
  ShopsShopIdCategoriesIndexRouteImport.update({
    id: '/shops/$shopId/categories/',
    path: '/shops/$shopId/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdBrandsIndexRoute = ShopsShopIdBrandsIndexRouteImport.update({
  id: '/shops/$shopId/brands/',
  path: '/shops/$shopId/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdTransactionsNewRoute =
  ShopsShopIdTransactionsNewRouteImport.update({
    id: '/shops/$shopId/transactions/new',
    path: '/shops/$shopId/transactions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdRefundsNewRoute = ShopsShopIdRefundsNewRouteImport.update({
  id: '/shops/$shopId/refunds/new',
  path: '/shops/$shopId/refunds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdProductsNewRoute = ShopsShopIdProductsNewRouteImport.update({
  id: '/shops/$shopId/products/new',
  path: '/shops/$shopId/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdPosSessionsNewRoute =
  ShopsShopIdPosSessionsNewRouteImport.update({
    id: '/shops/$shopId/pos-sessions/new',
    path: '/shops/$shopId/pos-sessions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdPaymentsNewRoute = ShopsShopIdPaymentsNewRouteImport.update({
  id: '/shops/$shopId/payments/new',
  path: '/shops/$shopId/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdOrdersNewRoute = ShopsShopIdOrdersNewRouteImport.update({
  id: '/shops/$shopId/orders/new',
  path: '/shops/$shopId/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdInventoryNewRoute = ShopsShopIdInventoryNewRouteImport.update({
  id: '/shops/$shopId/inventory/new',
  path: '/shops/$shopId/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdInventoryMovementsRoute =
  ShopsShopIdInventoryMovementsRouteImport.update({
    id: '/shops/$shopId/inventory/movements',
    path: '/shops/$shopId/inventory/movements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersNewRoute = ShopsShopIdCustomersNewRouteImport.update({
  id: '/shops/$shopId/customers/new',
  path: '/shops/$shopId/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdCheckoutsNewRoute = ShopsShopIdCheckoutsNewRouteImport.update({
  id: '/shops/$shopId/checkouts/new',
  path: '/shops/$shopId/checkouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdCategoriesNewRoute =
  ShopsShopIdCategoriesNewRouteImport.update({
    id: '/shops/$shopId/categories/new',
    path: '/shops/$shopId/categories/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdBrandsNewRoute = ShopsShopIdBrandsNewRouteImport.update({
  id: '/shops/$shopId/brands/new',
  path: '/shops/$shopId/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdCustomersGroupsIndexRoute =
  ShopsShopIdCustomersGroupsIndexRouteImport.update({
    id: '/shops/$shopId/customers/groups/',
    path: '/shops/$shopId/customers/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersAddressesIndexRoute =
  ShopsShopIdCustomersAddressesIndexRouteImport.update({
    id: '/shops/$shopId/customers/addresses/',
    path: '/shops/$shopId/customers/addresses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdTransactionsTransactionIdEditRoute =
  ShopsShopIdTransactionsTransactionIdEditRouteImport.update({
    id: '/shops/$shopId/transactions/$transactionId/edit',
    path: '/shops/$shopId/transactions/$transactionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdRefundsRefundIdEditRoute =
  ShopsShopIdRefundsRefundIdEditRouteImport.update({
    id: '/shops/$shopId/refunds/$refundId/edit',
    path: '/shops/$shopId/refunds/$refundId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdProductsProductIdEditRoute =
  ShopsShopIdProductsProductIdEditRouteImport.update({
    id: '/shops/$shopId/products/$productId/edit',
    path: '/shops/$shopId/products/$productId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdPosSessionsPosSessionIdEditRoute =
  ShopsShopIdPosSessionsPosSessionIdEditRouteImport.update({
    id: '/shops/$shopId/pos-sessions/$posSessionId/edit',
    path: '/shops/$shopId/pos-sessions/$posSessionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdPaymentsPaymentIdEditRoute =
  ShopsShopIdPaymentsPaymentIdEditRouteImport.update({
    id: '/shops/$shopId/payments/$paymentId/edit',
    path: '/shops/$shopId/payments/$paymentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdOrdersOrderIdEditRoute =
  ShopsShopIdOrdersOrderIdEditRouteImport.update({
    id: '/shops/$shopId/orders/$orderId/edit',
    path: '/shops/$shopId/orders/$orderId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdInventoryInventoryLevelIdEditRoute =
  ShopsShopIdInventoryInventoryLevelIdEditRouteImport.update({
    id: '/shops/$shopId/inventory/$inventoryLevelId/edit',
    path: '/shops/$shopId/inventory/$inventoryLevelId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersAddressesNewRoute =
  ShopsShopIdCustomersAddressesNewRouteImport.update({
    id: '/shops/$shopId/customers/addresses/new',
    path: '/shops/$shopId/customers/addresses/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersCustomerIdEditRoute =
  ShopsShopIdCustomersCustomerIdEditRouteImport.update({
    id: '/shops/$shopId/customers/$customerId/edit',
    path: '/shops/$shopId/customers/$customerId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCheckoutsCheckoutIdEditRoute =
  ShopsShopIdCheckoutsCheckoutIdEditRouteImport.update({
    id: '/shops/$shopId/checkouts/$checkoutId/edit',
    path: '/shops/$shopId/checkouts/$checkoutId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCategoriesCategoryIdEditRoute =
  ShopsShopIdCategoriesCategoryIdEditRouteImport.update({
    id: '/shops/$shopId/categories/$categoryId/edit',
    path: '/shops/$shopId/categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdBrandsBrandIdEditRoute =
  ShopsShopIdBrandsBrandIdEditRouteImport.update({
    id: '/shops/$shopId/brands/$brandId/edit',
    path: '/shops/$shopId/brands/$brandId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopsShopIdCustomersAddressesAddressIdEditRoute =
  ShopsShopIdCustomersAddressesAddressIdEditRouteImport.update({
    id: '/shops/$shopId/customers/addresses/$addressId/edit',
    path: '/shops/$shopId/customers/addresses/$addressId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/shops/new': typeof ShopsNewRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/add-module': typeof ShopsShopIdAddModuleRoute
  '/shops/$shopId/settings': typeof ShopsShopIdSettingsRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/brands/new': typeof ShopsShopIdBrandsNewRoute
  '/shops/$shopId/categories/new': typeof ShopsShopIdCategoriesNewRoute
  '/shops/$shopId/checkouts/new': typeof ShopsShopIdCheckoutsNewRoute
  '/shops/$shopId/customers/new': typeof ShopsShopIdCustomersNewRoute
  '/shops/$shopId/inventory/movements': typeof ShopsShopIdInventoryMovementsRoute
  '/shops/$shopId/inventory/new': typeof ShopsShopIdInventoryNewRoute
  '/shops/$shopId/orders/new': typeof ShopsShopIdOrdersNewRoute
  '/shops/$shopId/payments/new': typeof ShopsShopIdPaymentsNewRoute
  '/shops/$shopId/pos-sessions/new': typeof ShopsShopIdPosSessionsNewRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/refunds/new': typeof ShopsShopIdRefundsNewRoute
  '/shops/$shopId/transactions/new': typeof ShopsShopIdTransactionsNewRoute
  '/shops/$shopId/brands/': typeof ShopsShopIdBrandsIndexRoute
  '/shops/$shopId/categories/': typeof ShopsShopIdCategoriesIndexRoute
  '/shops/$shopId/checkouts/': typeof ShopsShopIdCheckoutsIndexRoute
  '/shops/$shopId/customers/': typeof ShopsShopIdCustomersIndexRoute
  '/shops/$shopId/inquiries/': typeof ShopsShopIdInquiriesIndexRoute
  '/shops/$shopId/inventory/': typeof ShopsShopIdInventoryIndexRoute
  '/shops/$shopId/locations/': typeof ShopsShopIdLocationsIndexRoute
  '/shops/$shopId/orders/': typeof ShopsShopIdOrdersIndexRoute
  '/shops/$shopId/payments/': typeof ShopsShopIdPaymentsIndexRoute
  '/shops/$shopId/pos-sessions/': typeof ShopsShopIdPosSessionsIndexRoute
  '/shops/$shopId/products/': typeof ShopsShopIdProductsIndexRoute
  '/shops/$shopId/refunds/': typeof ShopsShopIdRefundsIndexRoute
  '/shops/$shopId/reviews/': typeof ShopsShopIdReviewsIndexRoute
  '/shops/$shopId/shipments/': typeof ShopsShopIdShipmentsIndexRoute
  '/shops/$shopId/transactions/': typeof ShopsShopIdTransactionsIndexRoute
  '/shops/$shopId/brands/$brandId/edit': typeof ShopsShopIdBrandsBrandIdEditRoute
  '/shops/$shopId/categories/$categoryId/edit': typeof ShopsShopIdCategoriesCategoryIdEditRoute
  '/shops/$shopId/checkouts/$checkoutId/edit': typeof ShopsShopIdCheckoutsCheckoutIdEditRoute
  '/shops/$shopId/customers/$customerId/edit': typeof ShopsShopIdCustomersCustomerIdEditRoute
  '/shops/$shopId/customers/addresses/new': typeof ShopsShopIdCustomersAddressesNewRoute
  '/shops/$shopId/inventory/$inventoryLevelId/edit': typeof ShopsShopIdInventoryInventoryLevelIdEditRoute
  '/shops/$shopId/orders/$orderId/edit': typeof ShopsShopIdOrdersOrderIdEditRoute
  '/shops/$shopId/payments/$paymentId/edit': typeof ShopsShopIdPaymentsPaymentIdEditRoute
  '/shops/$shopId/pos-sessions/$posSessionId/edit': typeof ShopsShopIdPosSessionsPosSessionIdEditRoute
  '/shops/$shopId/products/$productId/edit': typeof ShopsShopIdProductsProductIdEditRoute
  '/shops/$shopId/refunds/$refundId/edit': typeof ShopsShopIdRefundsRefundIdEditRoute
  '/shops/$shopId/transactions/$transactionId/edit': typeof ShopsShopIdTransactionsTransactionIdEditRoute
  '/shops/$shopId/customers/addresses/': typeof ShopsShopIdCustomersAddressesIndexRoute
  '/shops/$shopId/customers/groups/': typeof ShopsShopIdCustomersGroupsIndexRoute
  '/shops/$shopId/customers/addresses/$addressId/edit': typeof ShopsShopIdCustomersAddressesAddressIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/shops/new': typeof ShopsNewRoute
  '/shops': typeof ShopsIndexRoute
  '/shops/$shopId/add-module': typeof ShopsShopIdAddModuleRoute
  '/shops/$shopId/settings': typeof ShopsShopIdSettingsRoute
  '/shops/$shopId': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/brands/new': typeof ShopsShopIdBrandsNewRoute
  '/shops/$shopId/categories/new': typeof ShopsShopIdCategoriesNewRoute
  '/shops/$shopId/checkouts/new': typeof ShopsShopIdCheckoutsNewRoute
  '/shops/$shopId/customers/new': typeof ShopsShopIdCustomersNewRoute
  '/shops/$shopId/inventory/movements': typeof ShopsShopIdInventoryMovementsRoute
  '/shops/$shopId/inventory/new': typeof ShopsShopIdInventoryNewRoute
  '/shops/$shopId/orders/new': typeof ShopsShopIdOrdersNewRoute
  '/shops/$shopId/payments/new': typeof ShopsShopIdPaymentsNewRoute
  '/shops/$shopId/pos-sessions/new': typeof ShopsShopIdPosSessionsNewRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/refunds/new': typeof ShopsShopIdRefundsNewRoute
  '/shops/$shopId/transactions/new': typeof ShopsShopIdTransactionsNewRoute
  '/shops/$shopId/brands': typeof ShopsShopIdBrandsIndexRoute
  '/shops/$shopId/categories': typeof ShopsShopIdCategoriesIndexRoute
  '/shops/$shopId/checkouts': typeof ShopsShopIdCheckoutsIndexRoute
  '/shops/$shopId/customers': typeof ShopsShopIdCustomersIndexRoute
  '/shops/$shopId/inquiries': typeof ShopsShopIdInquiriesIndexRoute
  '/shops/$shopId/inventory': typeof ShopsShopIdInventoryIndexRoute
  '/shops/$shopId/locations': typeof ShopsShopIdLocationsIndexRoute
  '/shops/$shopId/orders': typeof ShopsShopIdOrdersIndexRoute
  '/shops/$shopId/payments': typeof ShopsShopIdPaymentsIndexRoute
  '/shops/$shopId/pos-sessions': typeof ShopsShopIdPosSessionsIndexRoute
  '/shops/$shopId/products': typeof ShopsShopIdProductsIndexRoute
  '/shops/$shopId/refunds': typeof ShopsShopIdRefundsIndexRoute
  '/shops/$shopId/reviews': typeof ShopsShopIdReviewsIndexRoute
  '/shops/$shopId/shipments': typeof ShopsShopIdShipmentsIndexRoute
  '/shops/$shopId/transactions': typeof ShopsShopIdTransactionsIndexRoute
  '/shops/$shopId/brands/$brandId/edit': typeof ShopsShopIdBrandsBrandIdEditRoute
  '/shops/$shopId/categories/$categoryId/edit': typeof ShopsShopIdCategoriesCategoryIdEditRoute
  '/shops/$shopId/checkouts/$checkoutId/edit': typeof ShopsShopIdCheckoutsCheckoutIdEditRoute
  '/shops/$shopId/customers/$customerId/edit': typeof ShopsShopIdCustomersCustomerIdEditRoute
  '/shops/$shopId/customers/addresses/new': typeof ShopsShopIdCustomersAddressesNewRoute
  '/shops/$shopId/inventory/$inventoryLevelId/edit': typeof ShopsShopIdInventoryInventoryLevelIdEditRoute
  '/shops/$shopId/orders/$orderId/edit': typeof ShopsShopIdOrdersOrderIdEditRoute
  '/shops/$shopId/payments/$paymentId/edit': typeof ShopsShopIdPaymentsPaymentIdEditRoute
  '/shops/$shopId/pos-sessions/$posSessionId/edit': typeof ShopsShopIdPosSessionsPosSessionIdEditRoute
  '/shops/$shopId/products/$productId/edit': typeof ShopsShopIdProductsProductIdEditRoute
  '/shops/$shopId/refunds/$refundId/edit': typeof ShopsShopIdRefundsRefundIdEditRoute
  '/shops/$shopId/transactions/$transactionId/edit': typeof ShopsShopIdTransactionsTransactionIdEditRoute
  '/shops/$shopId/customers/addresses': typeof ShopsShopIdCustomersAddressesIndexRoute
  '/shops/$shopId/customers/groups': typeof ShopsShopIdCustomersGroupsIndexRoute
  '/shops/$shopId/customers/addresses/$addressId/edit': typeof ShopsShopIdCustomersAddressesAddressIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules': typeof ModulesRoute
  '/pairing': typeof PairingRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/shops/new': typeof ShopsNewRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/add-module': typeof ShopsShopIdAddModuleRoute
  '/shops/$shopId/settings': typeof ShopsShopIdSettingsRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/brands/new': typeof ShopsShopIdBrandsNewRoute
  '/shops/$shopId/categories/new': typeof ShopsShopIdCategoriesNewRoute
  '/shops/$shopId/checkouts/new': typeof ShopsShopIdCheckoutsNewRoute
  '/shops/$shopId/customers/new': typeof ShopsShopIdCustomersNewRoute
  '/shops/$shopId/inventory/movements': typeof ShopsShopIdInventoryMovementsRoute
  '/shops/$shopId/inventory/new': typeof ShopsShopIdInventoryNewRoute
  '/shops/$shopId/orders/new': typeof ShopsShopIdOrdersNewRoute
  '/shops/$shopId/payments/new': typeof ShopsShopIdPaymentsNewRoute
  '/shops/$shopId/pos-sessions/new': typeof ShopsShopIdPosSessionsNewRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/refunds/new': typeof ShopsShopIdRefundsNewRoute
  '/shops/$shopId/transactions/new': typeof ShopsShopIdTransactionsNewRoute
  '/shops/$shopId/brands/': typeof ShopsShopIdBrandsIndexRoute
  '/shops/$shopId/categories/': typeof ShopsShopIdCategoriesIndexRoute
  '/shops/$shopId/checkouts/': typeof ShopsShopIdCheckoutsIndexRoute
  '/shops/$shopId/customers/': typeof ShopsShopIdCustomersIndexRoute
  '/shops/$shopId/inquiries/': typeof ShopsShopIdInquiriesIndexRoute
  '/shops/$shopId/inventory/': typeof ShopsShopIdInventoryIndexRoute
  '/shops/$shopId/locations/': typeof ShopsShopIdLocationsIndexRoute
  '/shops/$shopId/orders/': typeof ShopsShopIdOrdersIndexRoute
  '/shops/$shopId/payments/': typeof ShopsShopIdPaymentsIndexRoute
  '/shops/$shopId/pos-sessions/': typeof ShopsShopIdPosSessionsIndexRoute
  '/shops/$shopId/products/': typeof ShopsShopIdProductsIndexRoute
  '/shops/$shopId/refunds/': typeof ShopsShopIdRefundsIndexRoute
  '/shops/$shopId/reviews/': typeof ShopsShopIdReviewsIndexRoute
  '/shops/$shopId/shipments/': typeof ShopsShopIdShipmentsIndexRoute
  '/shops/$shopId/transactions/': typeof ShopsShopIdTransactionsIndexRoute
  '/shops/$shopId/brands/$brandId/edit': typeof ShopsShopIdBrandsBrandIdEditRoute
  '/shops/$shopId/categories/$categoryId/edit': typeof ShopsShopIdCategoriesCategoryIdEditRoute
  '/shops/$shopId/checkouts/$checkoutId/edit': typeof ShopsShopIdCheckoutsCheckoutIdEditRoute
  '/shops/$shopId/customers/$customerId/edit': typeof ShopsShopIdCustomersCustomerIdEditRoute
  '/shops/$shopId/customers/addresses/new': typeof ShopsShopIdCustomersAddressesNewRoute
  '/shops/$shopId/inventory/$inventoryLevelId/edit': typeof ShopsShopIdInventoryInventoryLevelIdEditRoute
  '/shops/$shopId/orders/$orderId/edit': typeof ShopsShopIdOrdersOrderIdEditRoute
  '/shops/$shopId/payments/$paymentId/edit': typeof ShopsShopIdPaymentsPaymentIdEditRoute
  '/shops/$shopId/pos-sessions/$posSessionId/edit': typeof ShopsShopIdPosSessionsPosSessionIdEditRoute
  '/shops/$shopId/products/$productId/edit': typeof ShopsShopIdProductsProductIdEditRoute
  '/shops/$shopId/refunds/$refundId/edit': typeof ShopsShopIdRefundsRefundIdEditRoute
  '/shops/$shopId/transactions/$transactionId/edit': typeof ShopsShopIdTransactionsTransactionIdEditRoute
  '/shops/$shopId/customers/addresses/': typeof ShopsShopIdCustomersAddressesIndexRoute
  '/shops/$shopId/customers/groups/': typeof ShopsShopIdCustomersGroupsIndexRoute
  '/shops/$shopId/customers/addresses/$addressId/edit': typeof ShopsShopIdCustomersAddressesAddressIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modules'
    | '/pairing'
    | '/settings'
    | '/templates'
    | '/users'
    | '/shops/new'
    | '/shops/'
    | '/shops/$shopId/add-module'
    | '/shops/$shopId/settings'
    | '/shops/$shopId/'
    | '/shops/$shopId/brands/new'
    | '/shops/$shopId/categories/new'
    | '/shops/$shopId/checkouts/new'
    | '/shops/$shopId/customers/new'
    | '/shops/$shopId/inventory/movements'
    | '/shops/$shopId/inventory/new'
    | '/shops/$shopId/orders/new'
    | '/shops/$shopId/payments/new'
    | '/shops/$shopId/pos-sessions/new'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/refunds/new'
    | '/shops/$shopId/transactions/new'
    | '/shops/$shopId/brands/'
    | '/shops/$shopId/categories/'
    | '/shops/$shopId/checkouts/'
    | '/shops/$shopId/customers/'
    | '/shops/$shopId/inquiries/'
    | '/shops/$shopId/inventory/'
    | '/shops/$shopId/locations/'
    | '/shops/$shopId/orders/'
    | '/shops/$shopId/payments/'
    | '/shops/$shopId/pos-sessions/'
    | '/shops/$shopId/products/'
    | '/shops/$shopId/refunds/'
    | '/shops/$shopId/reviews/'
    | '/shops/$shopId/shipments/'
    | '/shops/$shopId/transactions/'
    | '/shops/$shopId/brands/$brandId/edit'
    | '/shops/$shopId/categories/$categoryId/edit'
    | '/shops/$shopId/checkouts/$checkoutId/edit'
    | '/shops/$shopId/customers/$customerId/edit'
    | '/shops/$shopId/customers/addresses/new'
    | '/shops/$shopId/inventory/$inventoryLevelId/edit'
    | '/shops/$shopId/orders/$orderId/edit'
    | '/shops/$shopId/payments/$paymentId/edit'
    | '/shops/$shopId/pos-sessions/$posSessionId/edit'
    | '/shops/$shopId/products/$productId/edit'
    | '/shops/$shopId/refunds/$refundId/edit'
    | '/shops/$shopId/transactions/$transactionId/edit'
    | '/shops/$shopId/customers/addresses/'
    | '/shops/$shopId/customers/groups/'
    | '/shops/$shopId/customers/addresses/$addressId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modules'
    | '/pairing'
    | '/settings'
    | '/templates'
    | '/users'
    | '/shops/new'
    | '/shops'
    | '/shops/$shopId/add-module'
    | '/shops/$shopId/settings'
    | '/shops/$shopId'
    | '/shops/$shopId/brands/new'
    | '/shops/$shopId/categories/new'
    | '/shops/$shopId/checkouts/new'
    | '/shops/$shopId/customers/new'
    | '/shops/$shopId/inventory/movements'
    | '/shops/$shopId/inventory/new'
    | '/shops/$shopId/orders/new'
    | '/shops/$shopId/payments/new'
    | '/shops/$shopId/pos-sessions/new'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/refunds/new'
    | '/shops/$shopId/transactions/new'
    | '/shops/$shopId/brands'
    | '/shops/$shopId/categories'
    | '/shops/$shopId/checkouts'
    | '/shops/$shopId/customers'
    | '/shops/$shopId/inquiries'
    | '/shops/$shopId/inventory'
    | '/shops/$shopId/locations'
    | '/shops/$shopId/orders'
    | '/shops/$shopId/payments'
    | '/shops/$shopId/pos-sessions'
    | '/shops/$shopId/products'
    | '/shops/$shopId/refunds'
    | '/shops/$shopId/reviews'
    | '/shops/$shopId/shipments'
    | '/shops/$shopId/transactions'
    | '/shops/$shopId/brands/$brandId/edit'
    | '/shops/$shopId/categories/$categoryId/edit'
    | '/shops/$shopId/checkouts/$checkoutId/edit'
    | '/shops/$shopId/customers/$customerId/edit'
    | '/shops/$shopId/customers/addresses/new'
    | '/shops/$shopId/inventory/$inventoryLevelId/edit'
    | '/shops/$shopId/orders/$orderId/edit'
    | '/shops/$shopId/payments/$paymentId/edit'
    | '/shops/$shopId/pos-sessions/$posSessionId/edit'
    | '/shops/$shopId/products/$productId/edit'
    | '/shops/$shopId/refunds/$refundId/edit'
    | '/shops/$shopId/transactions/$transactionId/edit'
    | '/shops/$shopId/customers/addresses'
    | '/shops/$shopId/customers/groups'
    | '/shops/$shopId/customers/addresses/$addressId/edit'
  id:
    | '__root__'
    | '/'
    | '/modules'
    | '/pairing'
    | '/settings'
    | '/templates'
    | '/users'
    | '/shops/new'
    | '/shops/'
    | '/shops/$shopId/add-module'
    | '/shops/$shopId/settings'
    | '/shops/$shopId/'
    | '/shops/$shopId/brands/new'
    | '/shops/$shopId/categories/new'
    | '/shops/$shopId/checkouts/new'
    | '/shops/$shopId/customers/new'
    | '/shops/$shopId/inventory/movements'
    | '/shops/$shopId/inventory/new'
    | '/shops/$shopId/orders/new'
    | '/shops/$shopId/payments/new'
    | '/shops/$shopId/pos-sessions/new'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/refunds/new'
    | '/shops/$shopId/transactions/new'
    | '/shops/$shopId/brands/'
    | '/shops/$shopId/categories/'
    | '/shops/$shopId/checkouts/'
    | '/shops/$shopId/customers/'
    | '/shops/$shopId/inquiries/'
    | '/shops/$shopId/inventory/'
    | '/shops/$shopId/locations/'
    | '/shops/$shopId/orders/'
    | '/shops/$shopId/payments/'
    | '/shops/$shopId/pos-sessions/'
    | '/shops/$shopId/products/'
    | '/shops/$shopId/refunds/'
    | '/shops/$shopId/reviews/'
    | '/shops/$shopId/shipments/'
    | '/shops/$shopId/transactions/'
    | '/shops/$shopId/brands/$brandId/edit'
    | '/shops/$shopId/categories/$categoryId/edit'
    | '/shops/$shopId/checkouts/$checkoutId/edit'
    | '/shops/$shopId/customers/$customerId/edit'
    | '/shops/$shopId/customers/addresses/new'
    | '/shops/$shopId/inventory/$inventoryLevelId/edit'
    | '/shops/$shopId/orders/$orderId/edit'
    | '/shops/$shopId/payments/$paymentId/edit'
    | '/shops/$shopId/pos-sessions/$posSessionId/edit'
    | '/shops/$shopId/products/$productId/edit'
    | '/shops/$shopId/refunds/$refundId/edit'
    | '/shops/$shopId/transactions/$transactionId/edit'
    | '/shops/$shopId/customers/addresses/'
    | '/shops/$shopId/customers/groups/'
    | '/shops/$shopId/customers/addresses/$addressId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
  PairingRoute: typeof PairingRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  ShopsNewRoute: typeof ShopsNewRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  ShopsShopIdAddModuleRoute: typeof ShopsShopIdAddModuleRoute
  ShopsShopIdSettingsRoute: typeof ShopsShopIdSettingsRoute
  ShopsShopIdIndexRoute: typeof ShopsShopIdIndexRoute
  ShopsShopIdBrandsNewRoute: typeof ShopsShopIdBrandsNewRoute
  ShopsShopIdCategoriesNewRoute: typeof ShopsShopIdCategoriesNewRoute
  ShopsShopIdCheckoutsNewRoute: typeof ShopsShopIdCheckoutsNewRoute
  ShopsShopIdCustomersNewRoute: typeof ShopsShopIdCustomersNewRoute
  ShopsShopIdInventoryMovementsRoute: typeof ShopsShopIdInventoryMovementsRoute
  ShopsShopIdInventoryNewRoute: typeof ShopsShopIdInventoryNewRoute
  ShopsShopIdOrdersNewRoute: typeof ShopsShopIdOrdersNewRoute
  ShopsShopIdPaymentsNewRoute: typeof ShopsShopIdPaymentsNewRoute
  ShopsShopIdPosSessionsNewRoute: typeof ShopsShopIdPosSessionsNewRoute
  ShopsShopIdProductsNewRoute: typeof ShopsShopIdProductsNewRoute
  ShopsShopIdRefundsNewRoute: typeof ShopsShopIdRefundsNewRoute
  ShopsShopIdTransactionsNewRoute: typeof ShopsShopIdTransactionsNewRoute
  ShopsShopIdBrandsIndexRoute: typeof ShopsShopIdBrandsIndexRoute
  ShopsShopIdCategoriesIndexRoute: typeof ShopsShopIdCategoriesIndexRoute
  ShopsShopIdCheckoutsIndexRoute: typeof ShopsShopIdCheckoutsIndexRoute
  ShopsShopIdCustomersIndexRoute: typeof ShopsShopIdCustomersIndexRoute
  ShopsShopIdInquiriesIndexRoute: typeof ShopsShopIdInquiriesIndexRoute
  ShopsShopIdInventoryIndexRoute: typeof ShopsShopIdInventoryIndexRoute
  ShopsShopIdLocationsIndexRoute: typeof ShopsShopIdLocationsIndexRoute
  ShopsShopIdOrdersIndexRoute: typeof ShopsShopIdOrdersIndexRoute
  ShopsShopIdPaymentsIndexRoute: typeof ShopsShopIdPaymentsIndexRoute
  ShopsShopIdPosSessionsIndexRoute: typeof ShopsShopIdPosSessionsIndexRoute
  ShopsShopIdProductsIndexRoute: typeof ShopsShopIdProductsIndexRoute
  ShopsShopIdRefundsIndexRoute: typeof ShopsShopIdRefundsIndexRoute
  ShopsShopIdReviewsIndexRoute: typeof ShopsShopIdReviewsIndexRoute
  ShopsShopIdShipmentsIndexRoute: typeof ShopsShopIdShipmentsIndexRoute
  ShopsShopIdTransactionsIndexRoute: typeof ShopsShopIdTransactionsIndexRoute
  ShopsShopIdBrandsBrandIdEditRoute: typeof ShopsShopIdBrandsBrandIdEditRoute
  ShopsShopIdCategoriesCategoryIdEditRoute: typeof ShopsShopIdCategoriesCategoryIdEditRoute
  ShopsShopIdCheckoutsCheckoutIdEditRoute: typeof ShopsShopIdCheckoutsCheckoutIdEditRoute
  ShopsShopIdCustomersCustomerIdEditRoute: typeof ShopsShopIdCustomersCustomerIdEditRoute
  ShopsShopIdCustomersAddressesNewRoute: typeof ShopsShopIdCustomersAddressesNewRoute
  ShopsShopIdInventoryInventoryLevelIdEditRoute: typeof ShopsShopIdInventoryInventoryLevelIdEditRoute
  ShopsShopIdOrdersOrderIdEditRoute: typeof ShopsShopIdOrdersOrderIdEditRoute
  ShopsShopIdPaymentsPaymentIdEditRoute: typeof ShopsShopIdPaymentsPaymentIdEditRoute
  ShopsShopIdPosSessionsPosSessionIdEditRoute: typeof ShopsShopIdPosSessionsPosSessionIdEditRoute
  ShopsShopIdProductsProductIdEditRoute: typeof ShopsShopIdProductsProductIdEditRoute
  ShopsShopIdRefundsRefundIdEditRoute: typeof ShopsShopIdRefundsRefundIdEditRoute
  ShopsShopIdTransactionsTransactionIdEditRoute: typeof ShopsShopIdTransactionsTransactionIdEditRoute
  ShopsShopIdCustomersAddressesIndexRoute: typeof ShopsShopIdCustomersAddressesIndexRoute
  ShopsShopIdCustomersGroupsIndexRoute: typeof ShopsShopIdCustomersGroupsIndexRoute
  ShopsShopIdCustomersAddressesAddressIdEditRoute: typeof ShopsShopIdCustomersAddressesAddressIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/new': {
      id: '/shops/new'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof ShopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/': {
      id: '/shops/$shopId/'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof ShopsShopIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/settings': {
      id: '/shops/$shopId/settings'
      path: '/shops/$shopId/settings'
      fullPath: '/shops/$shopId/settings'
      preLoaderRoute: typeof ShopsShopIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/add-module': {
      id: '/shops/$shopId/add-module'
      path: '/shops/$shopId/add-module'
      fullPath: '/shops/$shopId/add-module'
      preLoaderRoute: typeof ShopsShopIdAddModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/transactions/': {
      id: '/shops/$shopId/transactions/'
      path: '/shops/$shopId/transactions'
      fullPath: '/shops/$shopId/transactions/'
      preLoaderRoute: typeof ShopsShopIdTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/shipments/': {
      id: '/shops/$shopId/shipments/'
      path: '/shops/$shopId/shipments'
      fullPath: '/shops/$shopId/shipments/'
      preLoaderRoute: typeof ShopsShopIdShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/reviews/': {
      id: '/shops/$shopId/reviews/'
      path: '/shops/$shopId/reviews'
      fullPath: '/shops/$shopId/reviews/'
      preLoaderRoute: typeof ShopsShopIdReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/refunds/': {
      id: '/shops/$shopId/refunds/'
      path: '/shops/$shopId/refunds'
      fullPath: '/shops/$shopId/refunds/'
      preLoaderRoute: typeof ShopsShopIdRefundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/products/': {
      id: '/shops/$shopId/products/'
      path: '/shops/$shopId/products'
      fullPath: '/shops/$shopId/products/'
      preLoaderRoute: typeof ShopsShopIdProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/pos-sessions/': {
      id: '/shops/$shopId/pos-sessions/'
      path: '/shops/$shopId/pos-sessions'
      fullPath: '/shops/$shopId/pos-sessions/'
      preLoaderRoute: typeof ShopsShopIdPosSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/payments/': {
      id: '/shops/$shopId/payments/'
      path: '/shops/$shopId/payments'
      fullPath: '/shops/$shopId/payments/'
      preLoaderRoute: typeof ShopsShopIdPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/orders/': {
      id: '/shops/$shopId/orders/'
      path: '/shops/$shopId/orders'
      fullPath: '/shops/$shopId/orders/'
      preLoaderRoute: typeof ShopsShopIdOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/locations/': {
      id: '/shops/$shopId/locations/'
      path: '/shops/$shopId/locations'
      fullPath: '/shops/$shopId/locations/'
      preLoaderRoute: typeof ShopsShopIdLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/inventory/': {
      id: '/shops/$shopId/inventory/'
      path: '/shops/$shopId/inventory'
      fullPath: '/shops/$shopId/inventory/'
      preLoaderRoute: typeof ShopsShopIdInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/inquiries/': {
      id: '/shops/$shopId/inquiries/'
      path: '/shops/$shopId/inquiries'
      fullPath: '/shops/$shopId/inquiries/'
      preLoaderRoute: typeof ShopsShopIdInquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/': {
      id: '/shops/$shopId/customers/'
      path: '/shops/$shopId/customers'
      fullPath: '/shops/$shopId/customers/'
      preLoaderRoute: typeof ShopsShopIdCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/checkouts/': {
      id: '/shops/$shopId/checkouts/'
      path: '/shops/$shopId/checkouts'
      fullPath: '/shops/$shopId/checkouts/'
      preLoaderRoute: typeof ShopsShopIdCheckoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/categories/': {
      id: '/shops/$shopId/categories/'
      path: '/shops/$shopId/categories'
      fullPath: '/shops/$shopId/categories/'
      preLoaderRoute: typeof ShopsShopIdCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/brands/': {
      id: '/shops/$shopId/brands/'
      path: '/shops/$shopId/brands'
      fullPath: '/shops/$shopId/brands/'
      preLoaderRoute: typeof ShopsShopIdBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/transactions/new': {
      id: '/shops/$shopId/transactions/new'
      path: '/shops/$shopId/transactions/new'
      fullPath: '/shops/$shopId/transactions/new'
      preLoaderRoute: typeof ShopsShopIdTransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/refunds/new': {
      id: '/shops/$shopId/refunds/new'
      path: '/shops/$shopId/refunds/new'
      fullPath: '/shops/$shopId/refunds/new'
      preLoaderRoute: typeof ShopsShopIdRefundsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/products/new': {
      id: '/shops/$shopId/products/new'
      path: '/shops/$shopId/products/new'
      fullPath: '/shops/$shopId/products/new'
      preLoaderRoute: typeof ShopsShopIdProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/pos-sessions/new': {
      id: '/shops/$shopId/pos-sessions/new'
      path: '/shops/$shopId/pos-sessions/new'
      fullPath: '/shops/$shopId/pos-sessions/new'
      preLoaderRoute: typeof ShopsShopIdPosSessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/payments/new': {
      id: '/shops/$shopId/payments/new'
      path: '/shops/$shopId/payments/new'
      fullPath: '/shops/$shopId/payments/new'
      preLoaderRoute: typeof ShopsShopIdPaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/orders/new': {
      id: '/shops/$shopId/orders/new'
      path: '/shops/$shopId/orders/new'
      fullPath: '/shops/$shopId/orders/new'
      preLoaderRoute: typeof ShopsShopIdOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/inventory/new': {
      id: '/shops/$shopId/inventory/new'
      path: '/shops/$shopId/inventory/new'
      fullPath: '/shops/$shopId/inventory/new'
      preLoaderRoute: typeof ShopsShopIdInventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/inventory/movements': {
      id: '/shops/$shopId/inventory/movements'
      path: '/shops/$shopId/inventory/movements'
      fullPath: '/shops/$shopId/inventory/movements'
      preLoaderRoute: typeof ShopsShopIdInventoryMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/new': {
      id: '/shops/$shopId/customers/new'
      path: '/shops/$shopId/customers/new'
      fullPath: '/shops/$shopId/customers/new'
      preLoaderRoute: typeof ShopsShopIdCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/checkouts/new': {
      id: '/shops/$shopId/checkouts/new'
      path: '/shops/$shopId/checkouts/new'
      fullPath: '/shops/$shopId/checkouts/new'
      preLoaderRoute: typeof ShopsShopIdCheckoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/categories/new': {
      id: '/shops/$shopId/categories/new'
      path: '/shops/$shopId/categories/new'
      fullPath: '/shops/$shopId/categories/new'
      preLoaderRoute: typeof ShopsShopIdCategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/brands/new': {
      id: '/shops/$shopId/brands/new'
      path: '/shops/$shopId/brands/new'
      fullPath: '/shops/$shopId/brands/new'
      preLoaderRoute: typeof ShopsShopIdBrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/groups/': {
      id: '/shops/$shopId/customers/groups/'
      path: '/shops/$shopId/customers/groups'
      fullPath: '/shops/$shopId/customers/groups/'
      preLoaderRoute: typeof ShopsShopIdCustomersGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/addresses/': {
      id: '/shops/$shopId/customers/addresses/'
      path: '/shops/$shopId/customers/addresses'
      fullPath: '/shops/$shopId/customers/addresses/'
      preLoaderRoute: typeof ShopsShopIdCustomersAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/transactions/$transactionId/edit': {
      id: '/shops/$shopId/transactions/$transactionId/edit'
      path: '/shops/$shopId/transactions/$transactionId/edit'
      fullPath: '/shops/$shopId/transactions/$transactionId/edit'
      preLoaderRoute: typeof ShopsShopIdTransactionsTransactionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/refunds/$refundId/edit': {
      id: '/shops/$shopId/refunds/$refundId/edit'
      path: '/shops/$shopId/refunds/$refundId/edit'
      fullPath: '/shops/$shopId/refunds/$refundId/edit'
      preLoaderRoute: typeof ShopsShopIdRefundsRefundIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/products/$productId/edit': {
      id: '/shops/$shopId/products/$productId/edit'
      path: '/shops/$shopId/products/$productId/edit'
      fullPath: '/shops/$shopId/products/$productId/edit'
      preLoaderRoute: typeof ShopsShopIdProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/pos-sessions/$posSessionId/edit': {
      id: '/shops/$shopId/pos-sessions/$posSessionId/edit'
      path: '/shops/$shopId/pos-sessions/$posSessionId/edit'
      fullPath: '/shops/$shopId/pos-sessions/$posSessionId/edit'
      preLoaderRoute: typeof ShopsShopIdPosSessionsPosSessionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/payments/$paymentId/edit': {
      id: '/shops/$shopId/payments/$paymentId/edit'
      path: '/shops/$shopId/payments/$paymentId/edit'
      fullPath: '/shops/$shopId/payments/$paymentId/edit'
      preLoaderRoute: typeof ShopsShopIdPaymentsPaymentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/orders/$orderId/edit': {
      id: '/shops/$shopId/orders/$orderId/edit'
      path: '/shops/$shopId/orders/$orderId/edit'
      fullPath: '/shops/$shopId/orders/$orderId/edit'
      preLoaderRoute: typeof ShopsShopIdOrdersOrderIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/inventory/$inventoryLevelId/edit': {
      id: '/shops/$shopId/inventory/$inventoryLevelId/edit'
      path: '/shops/$shopId/inventory/$inventoryLevelId/edit'
      fullPath: '/shops/$shopId/inventory/$inventoryLevelId/edit'
      preLoaderRoute: typeof ShopsShopIdInventoryInventoryLevelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/addresses/new': {
      id: '/shops/$shopId/customers/addresses/new'
      path: '/shops/$shopId/customers/addresses/new'
      fullPath: '/shops/$shopId/customers/addresses/new'
      preLoaderRoute: typeof ShopsShopIdCustomersAddressesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/$customerId/edit': {
      id: '/shops/$shopId/customers/$customerId/edit'
      path: '/shops/$shopId/customers/$customerId/edit'
      fullPath: '/shops/$shopId/customers/$customerId/edit'
      preLoaderRoute: typeof ShopsShopIdCustomersCustomerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/checkouts/$checkoutId/edit': {
      id: '/shops/$shopId/checkouts/$checkoutId/edit'
      path: '/shops/$shopId/checkouts/$checkoutId/edit'
      fullPath: '/shops/$shopId/checkouts/$checkoutId/edit'
      preLoaderRoute: typeof ShopsShopIdCheckoutsCheckoutIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/categories/$categoryId/edit': {
      id: '/shops/$shopId/categories/$categoryId/edit'
      path: '/shops/$shopId/categories/$categoryId/edit'
      fullPath: '/shops/$shopId/categories/$categoryId/edit'
      preLoaderRoute: typeof ShopsShopIdCategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/brands/$brandId/edit': {
      id: '/shops/$shopId/brands/$brandId/edit'
      path: '/shops/$shopId/brands/$brandId/edit'
      fullPath: '/shops/$shopId/brands/$brandId/edit'
      preLoaderRoute: typeof ShopsShopIdBrandsBrandIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/customers/addresses/$addressId/edit': {
      id: '/shops/$shopId/customers/addresses/$addressId/edit'
      path: '/shops/$shopId/customers/addresses/$addressId/edit'
      fullPath: '/shops/$shopId/customers/addresses/$addressId/edit'
      preLoaderRoute: typeof ShopsShopIdCustomersAddressesAddressIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
  PairingRoute: PairingRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  ShopsNewRoute: ShopsNewRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  ShopsShopIdAddModuleRoute: ShopsShopIdAddModuleRoute,
  ShopsShopIdSettingsRoute: ShopsShopIdSettingsRoute,
  ShopsShopIdIndexRoute: ShopsShopIdIndexRoute,
  ShopsShopIdBrandsNewRoute: ShopsShopIdBrandsNewRoute,
  ShopsShopIdCategoriesNewRoute: ShopsShopIdCategoriesNewRoute,
  ShopsShopIdCheckoutsNewRoute: ShopsShopIdCheckoutsNewRoute,
  ShopsShopIdCustomersNewRoute: ShopsShopIdCustomersNewRoute,
  ShopsShopIdInventoryMovementsRoute: ShopsShopIdInventoryMovementsRoute,
  ShopsShopIdInventoryNewRoute: ShopsShopIdInventoryNewRoute,
  ShopsShopIdOrdersNewRoute: ShopsShopIdOrdersNewRoute,
  ShopsShopIdPaymentsNewRoute: ShopsShopIdPaymentsNewRoute,
  ShopsShopIdPosSessionsNewRoute: ShopsShopIdPosSessionsNewRoute,
  ShopsShopIdProductsNewRoute: ShopsShopIdProductsNewRoute,
  ShopsShopIdRefundsNewRoute: ShopsShopIdRefundsNewRoute,
  ShopsShopIdTransactionsNewRoute: ShopsShopIdTransactionsNewRoute,
  ShopsShopIdBrandsIndexRoute: ShopsShopIdBrandsIndexRoute,
  ShopsShopIdCategoriesIndexRoute: ShopsShopIdCategoriesIndexRoute,
  ShopsShopIdCheckoutsIndexRoute: ShopsShopIdCheckoutsIndexRoute,
  ShopsShopIdCustomersIndexRoute: ShopsShopIdCustomersIndexRoute,
  ShopsShopIdInquiriesIndexRoute: ShopsShopIdInquiriesIndexRoute,
  ShopsShopIdInventoryIndexRoute: ShopsShopIdInventoryIndexRoute,
  ShopsShopIdLocationsIndexRoute: ShopsShopIdLocationsIndexRoute,
  ShopsShopIdOrdersIndexRoute: ShopsShopIdOrdersIndexRoute,
  ShopsShopIdPaymentsIndexRoute: ShopsShopIdPaymentsIndexRoute,
  ShopsShopIdPosSessionsIndexRoute: ShopsShopIdPosSessionsIndexRoute,
  ShopsShopIdProductsIndexRoute: ShopsShopIdProductsIndexRoute,
  ShopsShopIdRefundsIndexRoute: ShopsShopIdRefundsIndexRoute,
  ShopsShopIdReviewsIndexRoute: ShopsShopIdReviewsIndexRoute,
  ShopsShopIdShipmentsIndexRoute: ShopsShopIdShipmentsIndexRoute,
  ShopsShopIdTransactionsIndexRoute: ShopsShopIdTransactionsIndexRoute,
  ShopsShopIdBrandsBrandIdEditRoute: ShopsShopIdBrandsBrandIdEditRoute,
  ShopsShopIdCategoriesCategoryIdEditRoute:
    ShopsShopIdCategoriesCategoryIdEditRoute,
  ShopsShopIdCheckoutsCheckoutIdEditRoute:
    ShopsShopIdCheckoutsCheckoutIdEditRoute,
  ShopsShopIdCustomersCustomerIdEditRoute:
    ShopsShopIdCustomersCustomerIdEditRoute,
  ShopsShopIdCustomersAddressesNewRoute: ShopsShopIdCustomersAddressesNewRoute,
  ShopsShopIdInventoryInventoryLevelIdEditRoute:
    ShopsShopIdInventoryInventoryLevelIdEditRoute,
  ShopsShopIdOrdersOrderIdEditRoute: ShopsShopIdOrdersOrderIdEditRoute,
  ShopsShopIdPaymentsPaymentIdEditRoute: ShopsShopIdPaymentsPaymentIdEditRoute,
  ShopsShopIdPosSessionsPosSessionIdEditRoute:
    ShopsShopIdPosSessionsPosSessionIdEditRoute,
  ShopsShopIdProductsProductIdEditRoute: ShopsShopIdProductsProductIdEditRoute,
  ShopsShopIdRefundsRefundIdEditRoute: ShopsShopIdRefundsRefundIdEditRoute,
  ShopsShopIdTransactionsTransactionIdEditRoute:
    ShopsShopIdTransactionsTransactionIdEditRoute,
  ShopsShopIdCustomersAddressesIndexRoute:
    ShopsShopIdCustomersAddressesIndexRoute,
  ShopsShopIdCustomersGroupsIndexRoute: ShopsShopIdCustomersGroupsIndexRoute,
  ShopsShopIdCustomersAddressesAddressIdEditRoute:
    ShopsShopIdCustomersAddressesAddressIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
